name: profinder_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  cloud_firestore: ^4.8.0
  get: ^4.6.1
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  curved_navigation_bar: any
  flame_audio: ^2.0.2
  flutter_signin_button: any
  metaballs: ^1.5.0
  multi_wizard: any
  flutter_onboarding_slider: ^1.0.9
  mockito: ^5.3.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #assets here images, fonts, etc
  assets:
    - assets/images/
